services:
  backend:
    build:
      context: ./dashboard/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./dashboard/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
